html/06e23cd6-aef8-4134-ac75-ced469967e74.html
html/085a9aed-417d-4ac5-bc66-2965c619d37b.html
html/08d9270b-9e73-448d-a039-fbdf4780eb79.html
html/30b8d5cb-5baa-46b3-aa7c-c41eae8c4948.html
html/3db4fed6-3e4d-4e1a-a991-2ef9b32b350c.html
html/4a5382b5-b3ed-44f1-a179-331187658026.html
html/6c01a9a3-f449-4e84-8796-f2b3bc955258.html
html/7ebe680c-f9fe-4ec0-9d20-0c326742df48.html
html/7ff28a99-f51f-484f-a8f4-520c909a1747.html
html/87071ebb-3027-49f1-906d-8c28bf14e3b6.html
html/a194d4a2-935c-474e-ac9b-229e0f990ea8.html
html/a24a80af-f99c-40ec-908f-52adf8691223.html
html/a69d8ebe-f5e0-439b-809a-238c1900816f.html
html/b39af80f-3579-43d1-8176-c28fe427801c.html
html/c2773885-1e6e-4c0d-9ddf-35cb900bfd77.html
html/ddd776e6-c6b7-45d8-b3a1-feaf3cee0c49.html
html/e9b37ef3-afd3-4822-ba36-b6268ce9922b.html

completed 7.2 changes level 0's

Viviane6 14 23

---

html/030ae31f-c3ab-4645-9770-89a76206876d.html
html/4a1c96c3-f69c-4a51-b90c-7a3370419e62.html
html/699c8b20-64aa-4e38-96a2-798f8858f597.html
html/70d43e24-da28-4e15-b0a0-e5f98104b6d4.html
html/808e6233-4518-45db-b937-09f987d27831.html
html/b4d2ed4e-8d4e-49a2-a42a-07b1465ccbaf.html
html/eeb152b0-50ef-487c-b82d-21a4a00d87ee.html

7.3 changes

---

html/19e2cc9c-dd28-4788-abef-02a0bff5d004.html
html/1d9dc9af-9032-46a9-b602-4772d0777274.html
html/4022cda6-e587-49cb-a1e0-26ef4f23f8fa.html
html/9871b2ec-67db-4a27-a82c-547cc191dee1.html
html/a44238cb-58e1-4c9b-acc3-15e89f044967.html
html/aa084809-eadc-4ae5-a25f-cd30e336613f.html
html/b62ed6a8-5f62-46c2-b7e5-00a810b4de27.html
html/bed2702a-600e-4d62-82b5-68ad1644ccf1.html
html/d201ed57-762b-468f-a63e-06812d5f6e0f.html
html/e7c89259-127d-4b4d-87bf-86b981d16892.html
html/eac0fa0a-f625-4e39-ba51-33a89daf7b8c.html

7.4 changes

---

html/06e23cd6-aef8-4134-ac75-ced469967e74.html
html/3a7b0916-1674-4746-a721-8994b72f706c.html
html/3db4fed6-3e4d-4e1a-a991-2ef9b32b350c.html
html/4659daf6-0d44-441d-873f-24a78f0abdac.html
html/51e39658-9c67-4a84-ac09-60e8922372f7.html
html/70d43e24-da28-4e15-b0a0-e5f98104b6d4.html
html/749ba7c1-2617-4997-9c6e-b86b476bac6c.html
html/76025d2c-4964-4ba2-9ec1-2d4d7602775c.html
html/797d63dc-8a13-4536-be74-e81221480950.html
html/b7ea3008-f387-418f-9061-5c7eee68aced.html
html/e7c89259-127d-4b4d-87bf-86b981d16892.html

7.5 changes and fixes for previous

---

html/28b690d6-ddb7-4f8d-a7a4-805f74585f29.html
html/376a4b95-24b4-4ab7-8957-d97397e2127f.html
html/3f701b27-9edb-48d9-a315-1c2393d9cdbe.html
html/a07feaec-fb46-49c4-88d8-68ba168a7444.html
html/b913a38a-e369-412d-8b93-8ecd52c8d401.html

Lishazavala1

---

html/030ae31f-c3ab-4645-9770-89a76206876d.html
html/085a9aed-417d-4ac5-bc66-2965c619d37b.html
html/1dabf768-8e72-4f75-9c72-7f2e46937752.html
html/4022cda6-e587-49cb-a1e0-26ef4f23f8fa.html
html/49739f54-f673-44c2-8e82-ed35ba373f4a.html
html/7ff28a99-f51f-484f-a8f4-520c909a1747.html
html/87071ebb-3027-49f1-906d-8c28bf14e3b6.html
html/9a7ee7b1-f43e-47f6-9c43-7c581e7a5a79.html
html/a194d4a2-935c-474e-ac9b-229e0f990ea8.html
html/a69d8ebe-f5e0-439b-809a-238c1900816f.html
html/af2d04f5-4652-41a6-bb28-502ea390e0ce.html
html/b4d2ed4e-8d4e-49a2-a42a-07b1465ccbaf.html
html/c2773885-1e6e-4c0d-9ddf-35cb900bfd77.html
html/e8669fb1-5717-490f-a15f-d73bc312435c.html
html/e9b37ef3-afd3-4822-ba36-b6268ce9922b.html
html/eac0fa0a-f625-4e39-ba51-33a89daf7b8c.html

fixed strong tags where applicable

fixed strong tags where applicable

---

html/002a35ca-0c06-4eb8-958c-1234ad4bed6b.html
html/01a64e34-4470-47e0-a9fa-a2953c02cd8b.html
html/084c5864-5246-4e17-b455-e91d0161b69e.html
html/1098aaf5-b663-4d7a-b8ac-d64118d4dc19.html
html/28b690d6-ddb7-4f8d-a7a4-805f74585f29.html
html/376a4b95-24b4-4ab7-8957-d97397e2127f.html
html/3f701b27-9edb-48d9-a315-1c2393d9cdbe.html
html/4650f0dc-0793-4f83-9a45-35f4dab77ff4.html
html/46e729f1-308d-458c-b8a7-e1c692815908.html
html/6622ece0-a389-4c41-8824-cd2fba96043e.html
html/989343f6-1c00-405d-87c7-6c2e30ef4b1f.html
html/a07feaec-fb46-49c4-88d8-68ba168a7444.html
html/aa6abfd6-23e0-4da8-91a7-3a19bf837b1d.html
html/ab14cd86-9008-4692-845c-000a76013301.html
html/af590687-247f-460b-9463-888422ae3bd7.html
html/b913a38a-e369-412d-8b93-8ecd52c8d401.html
html/bd6a4a3a-d4a3-4363-b248-0f22af3f31c7.html
html/caa8b884-4e07-4900-b1a9-c5fb3b8b04d8.html
html/dd0e1f0d-d271-4626-ab3c-ae1c63e06796.html
html/f7064cc6-9d60-4dd0-837a-6c769a7ece02.html
html/f9ac9daa-318e-4d91-a0da-26f1cddbc516.html

Updated 7.1 TG and SE. Went back to 6.6 and fixed p tags and bold

Lishazavala3

---

html/11d31e42-e3f2-4bb8-bc37-1e5be17b98bc.html
html/1ab548d6-346a-4478-a9a3-5f77d0e02871.html
html/260dcb95-e0a9-4d62-b85f-c4013389b87e.html
html/33f9d858-d7ed-458d-9e19-d293a9ce66b2.html
html/5e9ae24c-6b63-4dc2-bd08-9b185ca3c81a.html
html/73fbce4c-a86a-4ef5-8bdb-b006b282ec5e.html
html/7779b9ac-0b06-42f7-8f60-023b0124d6fb.html
html/8b3b7fb0-48e5-4f4e-8b4f-d81662512231.html
html/8f3d5ec5-3d85-41d4-90de-f3bae670af76.html
html/a66d46da-7ab4-44ee-9589-31d58681bcfe.html
html/afb3f309-da04-4a26-9162-74d8c7525d3d.html
html/b325ef44-18f7-49da-b96b-42893daf0bfa.html
html/c3870cbf-1276-4efa-9643-7bf4d476decd.html
html/cdf7a0c9-70ef-476a-8009-1542ae10a3a5.html
html/d77fb35c-d63a-4698-8585-b8406d46148d.html
html/d7c4b175-bca8-4d2b-84d4-7f104a179e66.html
html/dd7ad74f-5ff6-477e-9bf3-7eb59e88cb01.html
html/e0dcd1fd-8ac8-4a98-beef-a2c4f936ffbd.html
html/e619134a-a7cc-4593-aa8c-1cbd47d3c64d.html
html/f8147ce1-56c4-400a-b4b9-e8a2cfed8af4.html

7.12, 7.14, 7.16, and 8.1 changes

Viviane6 16 23

---

html/01cf42e1-8d70-4381-98b4-35382797806b.html
html/0a456b41-3d8e-468a-a992-038a35d790aa.html
html/17443858-a4f3-4cfb-80f5-3b67e4bc31f4.html
html/1c1e785e-e65f-426d-9c1b-17b137d0f6a6.html
html/234429aa-838b-4763-b1cb-7ac87402aaff.html
html/280a7278-dbb2-4f17-a2f8-77beb0dfad30.html
html/29deecd3-2363-4e83-862e-8f672be5a0da.html
html/34fefff8-4103-4c58-9047-51109416250e.html
html/35999a4d-621e-49cc-be68-348150fd0317.html
html/38011073-a5fa-4ed1-bf60-7cf2682e4010.html
html/47d7df0a-f0fc-4cca-8d23-894b19b458f5.html
html/51cf3910-86bd-4cea-b4c4-bcd13ef8ae6d.html
html/5a9b3336-58ac-43e0-8798-75824ab5f894.html
html/5bb45570-66af-4bb6-912f-966682d20319.html
html/5eaa50c9-cb2c-47a6-802d-132bc9f3ba01.html
html/825a70bd-f66f-4774-a2f0-097c5aaf23ef.html
html/83061887-e58c-4b56-bd53-196af10fb8a5.html
html/962d9894-add4-43b5-884b-7c8f64f46998.html
html/9852c8fb-872f-41ba-9a2d-679cc4c3ffa6.html
html/a27dcf8e-ffce-41cb-9931-5a01a36efb84.html
html/af76f461-26d4-4f21-bf94-aadd9eef9212.html
html/b4bab05a-254e-4916-817b-4caae61a939c.html
html/b946ee53-f6da-46a8-82c3-ae2884bd161f.html
html/c8ebc4b6-e2d2-44d2-b830-ffc75c063ae7.html
html/fc4150ab-28c5-4181-92e5-0890111d5546.html

7.9, 8.3,  and 8.4 changes done

Lishazavala4

---

html/000396d2-561e-40f3-aecf-86d8f79bb28f.html
html/1cf8a0a6-8e1c-4d49-a386-58f2173580b4.html
html/376a4b95-24b4-4ab7-8957-d97397e2127f.html
html/4381af70-0d93-4e66-a41e-18094e831d04.html
html/43aff004-37ac-4995-9eb6-6205724862b7.html
html/4940fdf4-9544-47e8-aa18-25bc0f191729.html
html/4d99343d-d66f-4109-8907-d93f930b3713.html
html/4ff49b1e-0724-427c-9789-7a17ecb2ea4b.html
html/6196b1a3-0206-45d5-a64a-eee5444840a5.html
html/635c3d59-c00f-44db-94be-03d8bb2fbf53.html
html/6622ece0-a389-4c41-8824-cd2fba96043e.html
html/7719ad4e-4682-42d4-9457-ed21b4b488b2.html
html/7b0de76c-f001-4662-bc2a-bf011193f8ea.html
html/825a70bd-f66f-4774-a2f0-097c5aaf23ef.html
html/83061887-e58c-4b56-bd53-196af10fb8a5.html
html/85461216-e0df-4e39-a22a-17368cc348cf.html
html/943bc677-b2a8-4ac7-8501-b0f5a8107cff.html
html/94ab3fd8-e15e-4cac-bf65-9d1058ed571f.html
html/9cdf1619-472c-4127-abfe-6b5bf5d9a2ad.html
html/ab14cd86-9008-4692-845c-000a76013301.html
html/b2769457-d920-4278-a885-71f067a48dfa.html
html/bc5ff775-1387-40e6-9564-f859e7be76f0.html
html/d2d045ba-1410-4709-bc61-dc1bd1e88e46.html
html/d3271028-421e-4423-816d-ca3de414d71e.html
html/e4fe071b-4ca2-4c4a-a68f-96a926e80679.html
html/fc4150ab-28c5-4181-92e5-0890111d5546.html

Updated 4.1, 4.3, and 4.9 with level 0 changes as well as fixed any comments from other lessons I previously worked on.

Lishazavala5

---

html/280a7278-dbb2-4f17-a2f8-77beb0dfad30.html
html/4381af70-0d93-4e66-a41e-18094e831d04.html
html/47d7df0a-f0fc-4cca-8d23-894b19b458f5.html
html/4940fdf4-9544-47e8-aa18-25bc0f191729.html
html/5a9b3336-58ac-43e0-8798-75824ab5f894.html
html/962d9894-add4-43b5-884b-7c8f64f46998.html
html/af76f461-26d4-4f21-bf94-aadd9eef9212.html
html/b4bab05a-254e-4916-817b-4caae61a939c.html
html/c8ebc4b6-e2d2-44d2-b830-ffc75c063ae7.html

Lishazavala7

---

html/07c539b4-2f56-4bfc-8ca4-fad2f7ee620f.html
html/0a4b1b15-18c0-4fee-89ed-6b40b4d8294f.html
html/0c9fb76d-b3e2-44f4-8dfd-e25f6934f3ea.html
html/0e3b42d7-9319-472d-9d87-a490f35ff9ac.html
html/1bd3d4bf-b430-4e21-9da4-da25e12ab6f2.html
html/1fb3c9c9-3e6b-4a3a-bfac-a8bab18b974e.html
html/2d82b08e-b664-4d4d-a8d1-4eb961cb876f.html
html/4a7400ed-5f15-49e1-8c87-646c2a6cc438.html
html/5983e49b-556d-4857-afff-4fce796245d0.html
html/66c37fb3-b5d8-4a85-9ff6-fe7abd10036e.html
html/66cb6088-dc92-4b4b-a0b8-14cdc2e0836a.html
html/6de09a9a-47ad-42cd-913b-e3931a6ee540.html
html/904da32a-bdd8-46d5-b613-02b297d3bb95.html
html/96870bbf-6b67-4dda-a571-57466240f356.html
html/9b47717f-226d-4a2a-8252-4eb69fc66a8e.html
html/9e85fb91-2c97-473c-8cc4-f9ee727a6370.html
html/aaa376b4-328f-4762-b6fe-d061f588b53c.html
html/b1cb6693-eace-440a-97f5-3cd690b4ca59.html
html/d819fae3-8eda-40a2-8690-e9b6f036e5d6.html
html/e9b16c51-82db-43de-9882-7023bd00f303.html
html/e9bfb3c6-7477-4fa3-9e09-76b533b37c4c.html
html/f422c30b-cb5b-4c95-9862-41acc10866f6.html
html/fbc2a63a-1040-4994-8fd2-059bc5631460.html
html/ff840f00-fff9-4ae7-a143-25d43c30cdac.html

did level 0 updates for 4.14, 5.2, and 5.10

Lishazavala8

---

html/01e6cf7a-9fcd-4bc5-ba36-0dcaab7aab10.html
html/1342f319-b523-4619-a84a-a4c57b0ebd7e.html
html/24aef4f7-6600-47b4-a008-57ec1905f531.html
html/641bae29-d837-4241-896f-4432a451f37b.html
html/64db040b-3f4e-4fe0-b715-5a58f3b314bc.html
html/ac4d5212-68b4-44d6-ab00-f510f7d53760.html
html/d28c3554-e0de-4a76-b421-e7c40a71a221.html
html/dca45446-7172-4719-8b84-11fe7a9d61e5.html
html/ec4996f5-4140-45d7-b9c2-d7795b32a951.html

Viviane6/24/23 5.15_OSXV2 Change

---

html/01a72df3-a600-4f47-b3d0-eeaee7c689de.html
html/186f01cb-350f-4ff1-a32b-9d264c41807e.html
html/2d638253-5726-4d9c-925a-830f69a3d6a2.html
html/345aaa10-b8e8-4b14-9424-abeaeaf394f6.html
html/6033726a-d3e4-4c31-8af1-536831df008c.html
html/61ec3576-c481-4523-85d8-cf4f8c4872bd.html
html/63376aa6-d3c2-4c1f-a803-f4e1c538824e.html
html/7755a937-c180-4d83-bd3b-d96f615e55e0.html
html/9379d00d-6361-4803-883c-bb25f3035cdc.html
html/b7b3b402-1e20-4e77-97e3-c66f50d49c50.html
html/c73e2112-12bf-4973-aa90-92d81b5750a7.html
html/d11f0413-114d-48db-9d75-87ed4620fc16.html
html/f54b456b-65ed-4d7f-82c1-a1f4709af4b1.html

Viviane6/24/23 1.2_OSXV2 Changes

---

html/0b0ed9de-bf08-485c-b9e5-9ed2a69dcee8.html
html/0cee3cbd-9935-4ca2-97b1-c3182fa74355.html
html/1098aaf5-b663-4d7a-b8ac-d64118d4dc19.html
html/1d470898-bb0e-4475-9129-f7c8c02ffbc6.html
html/1e12d41d-3db3-457c-866f-347eea031fc1.html
html/23bf685f-48d0-458f-8889-070f5270088a.html
html/26063b10-fd05-47b8-bd3d-cc26c934549d.html
html/30001553-158c-4a82-8981-a7c2353afe8d.html
html/3f51ec05-6474-4ccc-9d1a-d179d9e9e160.html
html/4a2012c0-3351-49e7-aad2-a0ca9a524b26.html
html/4b68e08f-7f48-44b4-bcaa-75c9a346d8f7.html
html/64063217-c48b-49fd-b2cc-ffef2170dba0.html
html/6622ece0-a389-4c41-8824-cd2fba96043e.html
html/6bbc6d01-e8ee-4eda-ad92-f13d22afda8d.html
html/6c30e34b-c01c-4734-8551-7f1c5dee9ece.html
html/7996ae74-795c-40ac-baaf-77bc2c9f0960.html
html/99d4617e-97e2-4728-9037-0d01792f559a.html
html/9a6a56ea-f90e-43be-ac0d-dca228502373.html
html/9cdf1619-472c-4127-abfe-6b5bf5d9a2ad.html
html/a00f4986-302e-4114-9121-9acf32aadbf4.html
html/a2cc13ed-7c08-43a0-8fb4-8939a07db185.html
html/a485c632-958a-40f4-ae0a-584914897d75.html
html/b2769457-d920-4278-a885-71f067a48dfa.html
html/bad595f3-fbc5-49ad-9854-00bfc65cd5d7.html
html/d618ef43-081e-4779-a612-932d6b927e0f.html
html/dd0e1f0d-d271-4626-ab3c-ae1c63e06796.html
html/dd14a30f-c171-43f8-ab90-c5cc042b6a29.html
html/e12150d4-5cbb-410f-99f8-47508c9f7e3f.html
html/e46cea96-c6b0-4bbb-b864-be586f984805.html
html/ee14c5e7-3149-4182-99df-4ecd7476c832.html

Level 0 changes for8.5, 8.9, and 5.3

Lishazavala10

---

html/048f15aa-52a3-43c6-b4f4-eb5547c9749f.html
html/08936867-584e-416d-a1d6-eaaea0febc88.html
html/141698a9-1e1b-43e0-806f-3a375cd0ce1b.html
html/1e8418e6-5ba4-4a6d-a534-a2a5d4aa4229.html
html/24aef4f7-6600-47b4-a008-57ec1905f531.html
html/4426cc2c-13ae-41b4-86fc-1dc631fb0df8.html
html/45b2c5d0-c08c-4262-8d8a-1bf24da7b3ae.html
html/4a7400ed-5f15-49e1-8c87-646c2a6cc438.html
html/5add7a2f-0af6-46ef-9f38-26014d80530f.html
html/703fbbf1-e1a3-4687-9ff7-931515ee8322.html
html/859d9080-f5ae-4b74-a33a-e9d4a6c47a13.html
html/a0bece79-75d0-4fd2-b9fa-787cc19d0614.html
html/a1c47bc8-38ff-48d5-8acb-f870cb34f195.html
html/cab31e2b-0a17-438d-b727-e9391725e66f.html
html/d19dd780-7b98-4dcd-8f0e-050fbd57532a.html
html/d68421ca-aa00-4b72-8eba-9e34edd2b38f.html
html/d7943784-f1ed-4463-9dba-7a2db8368a1b.html
html/f89e0577-e09a-4abd-a8ca-671d2df38749.html
html/fee39240-4420-45bf-bc9f-3fdf14f07d19.html

8.10, 8.11,and 9.1- and revisions

Viviane6 25 23 - 8.10, 8.11,and 9.1- and revisions

---

html/01604439-3ddf-4454-8113-ea3a6f9119b7.html
html/a89ae72f-e442-403c-a11a-62c7d363bf62.html
html/fd1fb70c-8732-4afd-91eb-ca89279805f0.html

Viviane6 25 23 9.2_OSXV2 Changes

---

html/212a31e1-062f-4c55-bbac-d6d2fee0943b.html
html/aaa2f2a1-7b0b-4526-b9a6-09ff8fce6871.html
html/bd8e7c3f-c2fb-4238-8906-3681fbab7b4f.html
html/e6ef31a5-cb61-4a24-a7df-6dd313dd59f9.html

Viviane6 25 23 9.3_OSXV2 Changes

---

html/1d6860c9-6536-4d6c-bb40-4034a218ec07.html
html/384915e1-4630-4145-98e8-cf1e5d99fb06.html
html/9fe5cecb-003e-4891-91a6-694fb74fb2bc.html

Viviane6 25 23 9.7_OSXV2 Changes

---

html/2ed98c9c-7be9-47f3-92d7-18cec04d3bd6.html
html/353d8c29-cc9f-4608-86cc-b09c124b1cbb.html
html/a387101f-0a6e-46a9-9fc3-75f47e6d4e80.html
html/dc778727-bcca-48ae-a1a0-2d38672969fa.html
html/dd7b07b9-01ba-46ff-9d17-243a3a3040c6.html
html/e78ae907-eb85-4629-8ea5-d2d550485df4.html

Viviane6 26 23b 7.6_OSXV2 Changes

---

html/08db1e07-8f50-46be-9f67-f1faf9d1f9f1.html
html/0c67c8db-a110-4b13-b861-67fb493f09ea.html
html/1502b2ad-0a66-41f3-aa35-9731b81256a5.html
html/3a582b7d-eed8-4839-93cd-697fc7268f01.html
html/507297b6-2ea7-4a5f-8864-296e2909da0d.html
html/7ad0767f-fc96-4897-8a4d-19bcaec075b1.html
html/cb52d3d5-e383-4a58-bae8-f14b8fc8dbeb.html
html/f60af193-c1e0-4041-962c-f379faf2a608.html

Viviane6 26 23b 8.6_OSXV2 Changes

---

html/149e5d4f-3e57-4642-9b4c-56850081fab4.html
html/b04ecb1e-996b-46f7-8eab-6c1f80389aac.html
html/d022800d-b439-41f7-9090-aad65e87360b.html
html/d585b5d1-2c3b-4890-90b4-43ca145ff60d.html
html/d7e22d6b-63cd-4d3b-9149-5cc054fc4876.html

Viviane6 26 23b 9.4_OSXV2 Changes

---

html/a2e8d7bf-f518-439a-a799-3c2c4e067c53.html
html/a545fab4-a80a-4155-9b5a-7fb561e32c47.html
html/ae48a550-0d12-448f-a15d-9d7d543500e1.html
html/df2b6ce2-e953-4307-9ba6-d208618e4df7.html
html/fb84a3b5-88e9-4918-bcef-5a89da45a3f1.html

Viviane6 27 23b revisions

---

html/297597ec-bb71-4433-a7e5-360066e5de33.html
html/771e2fc0-b7d3-4c84-8ba9-8c20a6e66e53.html
html/a387101f-0a6e-46a9-9fc3-75f47e6d4e80.html
html/ae78ce26-a525-4914-be21-363146fe1c25.html
html/d77e0909-5dae-4718-802c-60a75c521bd2.html

Viviane6 28 9=23b 1.3_OSXV2 partial changes

---

html/297597ec-bb71-4433-a7e5-360066e5de33.html
html/2c5b0bc8-bd05-4b1b-b223-141b38b92776.html
html/30d46b1e-86c3-4c6f-8ede-50105b0cb7fc.html
html/45b1f2c1-255e-45ad-94c7-d1a81cc69250.html
html/5640e477-e318-4f13-8f54-08b64590dabf.html
html/64c1ec6f-6486-427c-9bb8-b843cc676385.html
html/842820ad-0369-46f6-8c41-e9bc983abb6d.html
html/8bed2a8d-6c06-44ae-82b2-d79406a6ed77.html
html/b7a81fce-8472-4905-9389-0eca3594da38.html
html/d6e643f6-bb43-4ee5-8ad6-680131cc7f02.html
html/d77e0909-5dae-4718-802c-60a75c521bd2.html
html/e44ec8ee-ac66-4cfc-891c-110cfac52b10.html
html/eb8c88fb-4a2b-46f3-9e3c-4f531569ffcb.html
html/ee376826-4ee3-4f63-832c-aa6b05d0017b.html

Viviane6 28 23c 1.3_OSXV2 Changes

---

html/30d46b1e-86c3-4c6f-8ede-50105b0cb7fc.html
html/842820ad-0369-46f6-8c41-e9bc983abb6d.html
html/b7a81fce-8472-4905-9389-0eca3594da38.html
html/e44ec8ee-ac66-4cfc-891c-110cfac52b10.html

Viviane6 29 23 1.3.4 revisions

---

html/5a9b3336-58ac-43e0-8798-75824ab5f894.html
html/a27dcf8e-ffce-41cb-9931-5a01a36efb84.html

7.9.3 (SE)(TG) revision

---

html/0705c592-8f25-47cb-ae23-625fb735cf2f.html
html/12702f20-bb71-4741-9a07-3175a8c2e3d5.html
html/31a14d3f-4dfb-4849-97b5-fed692409130.html
html/3c2da165-7665-4087-8aff-eb3a289b5630.html
html/44009294-94d5-43f0-8596-28fcd5d51c02.html
html/55bca233-c529-4690-b0b2-fb2fae4cf707.html
html/62776785-ba07-4f7a-a91c-fbdb27150023.html
html/9cf765e3-a3a8-4b50-8a38-97e2a989cedd.html
html/ab4fdfea-3a34-45ba-974a-7c06172284b9.html
html/bbc65d33-3db1-4066-9b78-ba254811c72e.html
html/c7813f2c-8093-480c-ba39-12a5d7b682f8.html
html/c796acb0-197d-4f30-b8cd-25eac259e0a0.html
html/cf48a869-727e-4a18-adab-51531513e65f.html

Viviane6 30 23 1.4_OSXV2 Changes

---

html/0a4b1b15-18c0-4fee-89ed-6b40b4d8294f.html
html/6de09a9a-47ad-42cd-913b-e3931a6ee540.html

5.2.2 (SE)(TG) revisions

---

html/75a39b87-1fea-4d7a-a375-1de9387c23b5.html
html/b946fbf7-2289-4edc-8be3-e46d6a7e7674.html
html/bc9d46f7-9398-40f3-b1bd-0a8d90b7c3da.html
html/c0711258-cccd-4ab7-bc11-7dac09aaf1ef.html
html/c91a55b2-9604-453c-b2e2-6223d0d7723e.html
html/d330634e-2749-484a-8acb-629b412c3ed0.html
html/dcbba9b0-1753-42d4-95b4-4c2b431f61e0.html
html/fefe63e6-720c-43d5-986a-3d6b9ce075d5.html

Viviane7 1 23 4.6_OSXV2 Changes

---

html/31a14d3f-4dfb-4849-97b5-fed692409130.html
html/44009294-94d5-43f0-8596-28fcd5d51c02.html
html/ab4fdfea-3a34-45ba-974a-7c06172284b9.html
html/c7813f2c-8093-480c-ba39-12a5d7b682f8.html
html/c796acb0-197d-4f30-b8cd-25eac259e0a0.html

1.4_OSXV2 revisions

---

html/0732e928-c0ff-4a26-bc69-bcac7c17fdde.html
html/0d23bf92-90cd-41cc-80ec-f758316001d1.html
html/0d859f2b-0e69-4bb4-b08f-4c17b228c8ac.html
html/1fa58982-2978-42da-8576-ff21c53c5868.html
html/5424415e-a109-41c0-9aab-9ae0f45503e7.html
html/5870abb1-e65a-47ba-bc28-7cd8692680cd.html
html/5c76dbe6-107b-4b99-80d0-faa41127c89c.html
html/75fe3ec6-7faf-4258-8da1-4a4efbbd2b3c.html
html/a3b7a9e1-ee65-4afc-83ba-c36d026b1470.html
html/a7c944f7-7aa6-4a91-9a7b-3cc2e253dde2.html
html/bbe9b804-93cf-4930-a126-79114fd7a9af.html
html/cf81abb1-27c4-460c-aeb0-a773aa3d4732.html
html/d43cc6be-2fce-469f-859b-03bfaa12f2c9.html
html/f85235f8-402e-4ac7-944b-01a7c2248bef.html

Viviane7 1 23 4.7_OSXV2 Changes

---

html/00bd57a9-c35b-4f9d-91e1-7a913abeabe6.html
html/145430d3-4236-4adb-a82e-0cad443ff6f4.html
html/4aa49e21-6712-4dc9-8872-53951f2f0a26.html
html/9695369c-6554-4d3a-88ab-7617d675c9f7.html

Viviane7 1 23 1.5_OSXV2 TG changes

---

html/06fe1cdd-7f47-4625-a043-9ea1ebeca625.html
html/357a0e1c-9e27-4296-a515-6d35c0867543.html
html/4684fcc7-04d0-4383-8352-37c52819b817.html
html/4a1cc3e7-60d6-4420-81d7-5dc284a291b6.html
html/675ed2db-5543-4e55-83a8-5b6ad5882ad9.html
html/6fbb32e9-f411-4ac6-97b1-d323c504e0be.html
html/73be49ec-313b-4324-a870-8ef191bc6046.html
html/7ad312a6-962d-4c3d-8aaf-f7961bab3573.html
html/963627f8-bd68-4168-823e-a736a1384f35.html
html/97c941ea-ef79-4ded-8c71-b92e92f0da6a.html
html/9825d5e1-3fb6-460a-8404-796992138600.html
html/c0535197-037a-47c5-ae64-2f23ed06ee24.html
html/c0887a08-6ddd-41d0-9589-d482101a5700.html
html/cdec2a59-32ed-45a6-a23a-edca94b5c7f1.html
html/e0c84508-d9d5-4830-b9cc-380f369e8fc5.html
html/fd3eedb9-c26a-413a-8516-5636e85f4ecd.html
html/fff84583-1d24-41b9-8845-6c677dcfaf08.html

Lishazavala12

---

html/00bd57a9-c35b-4f9d-91e1-7a913abeabe6.html
html/0a4b1b15-18c0-4fee-89ed-6b40b4d8294f.html
html/145430d3-4236-4adb-a82e-0cad443ff6f4.html
html/639dac42-373d-4a0c-b20f-e81f7cfa2300.html
html/6de09a9a-47ad-42cd-913b-e3931a6ee540.html
html/cd7d3f77-eef9-4444-ae73-1111ce7329fc.html
html/e11744f2-a342-4033-a400-4af15d006d04.html
html/e80a4df0-0e10-415e-886d-037a9bf73f39.html

Viviane7 2 23 1.5_OSXV2 changes

---

html/3bc8a260-d6e6-484d-b1a1-e5aa9db0dc94.html
html/674c67a2-8e67-4783-9c32-02d2c935aed6.html
html/b11021bc-79b9-4234-afce-d36ac48432e8.html
html/fd6351fa-54e4-4416-96bd-62d095c992bf.html

Viviane7 2 23  1.6_OSXV2 TG changes

---

html/0deaea55-8ef9-43c5-a746-a53c0a739095.html
html/34b8b36c-99d8-4655-9f22-0e54769961ec.html
html/4dfe35d9-6673-4874-b721-36d2eadc966d.html
html/59980e73-fed7-4051-8d50-ddec85ea848d.html
html/6c2e14d6-ec41-4c94-b614-3873413aa0f5.html
html/8508959d-f488-4f93-93ad-918da4a3cebe.html
html/b11021bc-79b9-4234-afce-d36ac48432e8.html
html/be8edf3c-811d-4383-9482-a0f74f91f81d.html
html/ebcc588b-442e-4b21-ba18-e8b1b0adef7a.html
html/ece1567b-0408-414d-9e1e-0c2a72b382ed.html
html/fd6351fa-54e4-4416-96bd-62d095c992bf.html

Viviane7 2 23 1.6_OSXV2 Changes

---

html/4239324d-e383-4e48-8700-c68ade3c5305.html
html/7384dac4-f18d-489a-bee9-85f86ba53a24.html
html/87204cd8-36a5-419d-abc8-8d3dbe5ff827.html
html/8f9d899d-c04a-448f-aa91-7431b264f001.html
html/93c2be04-8cd8-4f02-b97a-94ee188f11ce.html
html/bcd97e70-ed43-4a35-b8ee-85675564d89a.html

Viviane7 3 23 1.7_OSXV2 TG HTML/Table fixes

---

html/1f9e8458-0d5f-4d4c-b3db-3578d88a7428.html
html/568d8097-a8e1-40e0-a1df-72ba4d1d5a98.html
html/aedb0913-a0ca-422b-bbe9-abce08512c94.html
html/b10a20f1-3653-40ee-a5b6-27799b84b829.html
html/d3cb02d9-d96c-4fa1-bbf3-ab069a184ce1.html

Viviane7 3 23 1.7_OSXV2 SE HTML/Table fixes

---

html/c91a55b2-9604-453c-b2e2-6223d0d7723e.html
html/d330634e-2749-484a-8acb-629b412c3ed0.html
html/dcbba9b0-1753-42d4-95b4-4c2b431f61e0.html
html/fefe63e6-720c-43d5-986a-3d6b9ce075d5.html

Viviane7 3 23 4.6_OSXV2 revisions

---

html/0d23bf92-90cd-41cc-80ec-f758316001d1.html
html/5870abb1-e65a-47ba-bc28-7cd8692680cd.html
html/5c76dbe6-107b-4b99-80d0-faa41127c89c.html
html/d43cc6be-2fce-469f-859b-03bfaa12f2c9.html

4.7_OSXV2  revisions

---

html/97c941ea-ef79-4ded-8c71-b92e92f0da6a.html
html/fff84583-1d24-41b9-8845-6c677dcfaf08.html

5.6_OSXV2 revisions

---

html/0e01d382-c0c0-4cd8-bc4e-23acf7cf58dc.html
html/3107b4b5-170a-4fc4-bc4f-dee2caa0e850.html
html/3142e865-b01e-4454-b0e4-95411a409889.html
html/8a520b7e-192f-4229-bf44-058c5798b477.html
html/93417e34-e4ad-4240-8c67-f35fe01eb773.html
html/a1d98125-0fba-4dc3-9f1c-c45332e91545.html
html/a2d622df-aa8a-49bc-8b87-e45200ee9a6a.html
html/f7913271-ce3f-4f4d-baf4-0c75a8790351.html

Viviane7 3 23 3.1_OSXV2 TG HTML/Tables

---

html/1fd302d8-2043-4833-945b-0f4e0a4892e6.html
html/858f4188-2f31-4dca-8923-9d0e6d69037a.html
html/8e9d9a93-988a-4d8b-9df8-b3632b96ca36.html
html/93417e34-e4ad-4240-8c67-f35fe01eb773.html
html/a2424502-8f9a-47f7-a7c3-400c3d86cc23.html
html/a3199718-cc11-43b3-baec-9cac85d47340.html
html/af42da40-6405-484f-9901-e20799040a12.html
html/d013660f-3672-434e-8c03-4779aa577260.html
html/d1f1760e-2284-406c-86ec-a4056ecbf4a8.html

Viviane7 3 23 3.1_OSXV2 SE html/tables

---

html/236c9455-64d0-49d6-b7bb-de067f955657.html
html/25ed3bfa-ab94-416a-bfb3-65582b3e5235.html
html/53185bb2-edf3-4c6c-8dbe-003e1bb58b6f.html
html/9b75f40a-0ed3-4bff-a8bb-857d379213a4.html
html/9d3a3ac2-3766-4254-94f0-39d98232e1bf.html
html/fef80c01-afb2-4af5-8748-fba7b3cb8b78.html

Viviane7 4 23 3.2_OSXV2 TG tables/changes

---

html/3c70e45d-be83-4224-ac86-61cc4551a825.html
html/5e69f4ad-cd83-4f36-b4a5-a4c1563c384f.html
html/9469bdb7-c10e-4381-ad09-c3ad374859ff.html
html/9d3a3ac2-3766-4254-94f0-39d98232e1bf.html
html/9fe968fb-439a-4c3d-b77f-497862df8da4.html
html/bf508937-e609-4edf-b788-bd9882a25bbf.html
html/c2556494-249b-4422-835f-3be8c1a2f2b1.html
html/cdd1f599-5765-45b1-978a-5f4a086143bf.html

Viviane7 4 23 3.2_OSXV2 sE tables/changes

---

html/3fde002b-bf85-4007-a396-6a59041e56df.html
html/40fa4d46-0296-43fd-befb-e58ae2326fe3.html
html/46245976-a55c-4160-9741-66021e3e45ee.html
html/4630f2be-00aa-4cf8-a231-1a4728897166.html
html/4ebb1fa2-0be4-4f16-a6b9-e1d03847a1cd.html
html/7b0f6075-e3cc-4f3d-ad37-454862277bd8.html
html/afe9280f-4e52-408f-a585-3e9521226e6a.html
html/c95d001e-3f53-479a-aeb1-68493f8a4b2b.html
html/ded25b85-676f-463d-9cb5-a398633c4919.html
html/ee0baed5-b6c3-4844-95f3-5dd02ad727a4.html
html/fc299aaf-71bc-4f81-a3b2-efc6d4a187bd.html

Lishazavala13

---

html/1b9100be-2004-4947-84ba-f44a5b5fc6a3.html
html/1efaa372-0796-4819-9161-d25f8350e651.html
html/47023f4c-88f9-4029-a99c-a98d17772b7b.html
html/5226a217-7e28-4ff8-bc60-8ce4bb80a896.html
html/91ba4f77-c324-40d7-80dc-ef2c16aa2181.html
html/ad0001df-c13b-4502-896f-e9154e963628.html
html/fe9a1406-e536-4343-a128-7c1a979b7eaf.html

Viviane7 4 23b 1.8_OSXV2 TG html tables

---

html/051de1b7-c33e-4428-a7e2-e1a8a4f0444b.html
html/0e2c67ad-5b10-4c0d-8256-74ae3d5f6f10.html
html/1b9100be-2004-4947-84ba-f44a5b5fc6a3.html
html/388b9913-1eeb-4fd8-869e-c1d4434dc31a.html
html/489b4b5d-920a-4d72-afa4-501a96110c6f.html
html/4eeea81c-6424-4d4c-8f28-51aaa536d9ce.html
html/6023a5a0-8a56-4475-8b28-689cfcd423aa.html
html/91ba4f77-c324-40d7-80dc-ef2c16aa2181.html
html/966c996f-29ee-4f34-8e91-f9e9cdc6b62d.html
html/e37fa3cb-488e-4172-9b81-e72fbaddfdc7.html

Viviane7 4 23b 1.8_OSXV2 SE html/tables

---

html/5a9b3336-58ac-43e0-8798-75824ab5f894.html
html/a27dcf8e-ffce-41cb-9931-5a01a36efb84.html

7.9.3 (SE)(TG) table update

---

html/2bc126b6-d986-49e0-b098-2ca3f75d41eb.html
html/3d891449-bf36-4ab8-97b8-87fa850f513c.html
html/53024e0d-44f8-4c1a-88cf-e902458ce581.html
html/799b56e8-4abd-4efa-852f-71bea1c09e77.html
html/a9244ce9-8fee-425e-8c75-c393439f04af.html
html/ab7cfe07-f761-45a4-b2be-64a58185e8ce.html
html/e69e03e7-1dc7-4ec4-b44e-9317a17a54e3.html

Viviane7 5 23 1.9_OSXV2 TG Changes

---

html/228e115e-3e86-40ff-aa5f-6adebc0b3fac.html
html/2bc126b6-d986-49e0-b098-2ca3f75d41eb.html
html/3d891449-bf36-4ab8-97b8-87fa850f513c.html
html/53024e0d-44f8-4c1a-88cf-e902458ce581.html
html/5c3c3d50-f9aa-43c3-aa1c-b592c5038cd3.html
html/799b56e8-4abd-4efa-852f-71bea1c09e77.html
html/87b1a9d1-7c96-46d7-88d6-ad6f523b1b37.html
html/a3eb3c57-dc2b-4269-88c5-0a9adb18feb8.html
html/a9244ce9-8fee-425e-8c75-c393439f04af.html
html/ba75e12d-6755-4b0f-9c50-fe13da520015.html
html/d05ee467-caa3-4953-bebc-ae1efe8bed15.html
html/df9b3633-019e-453b-9c0b-0b80e35ff02d.html
html/e69e03e7-1dc7-4ec4-b44e-9317a17a54e3.html
html/f5318ead-db2f-44f6-a3c2-8cafc1740310.html

Viviane7 5 23 1.9_OSXV2 SE changes

---

html/145430d3-4236-4adb-a82e-0cad443ff6f4.html
html/524ddb89-02a9-4381-a712-abbe37a96109.html
html/9695369c-6554-4d3a-88ab-7617d675c9f7.html
html/98243733-e56d-4e0f-a3bc-d5c2a6919c3e.html

Viviane7 5 23 1.5_OSXV2 TG changes

---

html/0dbff3c2-3791-4f01-98d6-5c9f8224179d.html
html/27e40302-18e9-4b1f-9411-5cc604107af2.html
html/3a7b0916-1674-4746-a721-8994b72f706c.html
html/4022cda6-e587-49cb-a1e0-26ef4f23f8fa.html
html/4f633a41-6184-4b48-9004-65c95b5681e7.html
html/70d43e24-da28-4e15-b0a0-e5f98104b6d4.html
html/749ba7c1-2617-4997-9c6e-b86b476bac6c.html
html/8afd0d02-0187-4458-8958-cf7f2d849f86.html
html/9871b2ec-67db-4a27-a82c-547cc191dee1.html
html/c2cfb498-3510-4188-bd7b-a7371198aa8c.html
html/e6ef31a5-cb61-4a24-a7df-6dd313dd59f9.html
html/e8fa961a-9730-4152-bd30-0f7309830e26.html
html/eac0fa0a-f625-4e39-ba51-33a89daf7b8c.html
html/f25f0afa-6a1a-4794-ba10-4571d7a61f5c.html

Revisions for 7.3, 7.4 and 7.5. Level 3 changes for 3.3TG only

Lishazavala14

---

html/b11021bc-79b9-4234-afce-d36ac48432e8.html
html/fd6351fa-54e4-4416-96bd-62d095c992bf.html

Viviane7 6 231.6_OSXV2 TG changes

---

html/4dfe35d9-6673-4874-b721-36d2eadc966d.html
html/6c2e14d6-ec41-4c94-b614-3873413aa0f5.html
html/84466c8d-ae93-49b6-b09f-82fb08f241ff.html
html/b11021bc-79b9-4234-afce-d36ac48432e8.html
html/ece1567b-0408-414d-9e1e-0c2a72b382ed.html
html/fd6351fa-54e4-4416-96bd-62d095c992bf.html

Viviane7 6 23 1.6_OSXV2 SE Changes

---

html/496bd09d-38ea-402c-86c5-9e9855519292.html
html/73faf22a-5d1f-49bf-9ab1-fb5d05d29bb8.html
html/b1604ec1-a906-4006-9e88-6f9cc3b24c54.html
html/c38f248c-675d-4b19-a888-075807107956.html

1.11.0, 1.11.1, 1.11.2, and 1.11.3 TG level 3 changes.

Lishazavala15

---

html/0e2c67ad-5b10-4c0d-8256-74ae3d5f6f10.html
html/1b9100be-2004-4947-84ba-f44a5b5fc6a3.html
html/1efaa372-0796-4819-9161-d25f8350e651.html
html/388b9913-1eeb-4fd8-869e-c1d4434dc31a.html
html/489b4b5d-920a-4d72-afa4-501a96110c6f.html
html/4eeea81c-6424-4d4c-8f28-51aaa536d9ce.html
html/6023a5a0-8a56-4475-8b28-689cfcd423aa.html
html/91ba4f77-c324-40d7-80dc-ef2c16aa2181.html
html/966c996f-29ee-4f34-8e91-f9e9cdc6b62d.html
html/e37fa3cb-488e-4172-9b81-e72fbaddfdc7.html

Viviane7 7 23 1.8_OSXV2 SE changes

---

html/3fc2397e-6ed9-4bb6-913a-ad80245c6c3a.html

1.5  fixes 1.5_OSXV2 

---

html/ebcc588b-442e-4b21-ba18-e8b1b0adef7a.html
html/fd6351fa-54e4-4416-96bd-62d095c992bf.html

1.6.3 (SE)(TG) changes 1.6_OSXV2 

---

html/629a95ac-3780-43dd-bf6f-91c2242e10a2.html
html/c635ad79-99e8-462b-9cb2-f6eaab10a515.html
html/df9f55fd-8f35-4e7d-8de8-23982bb05091.html

Viviane7 7 23 2.1_OSXV2 partial tg

---

html/1a1e54a8-ab5d-4bf0-9b0c-eae0405adb47.html
html/629a95ac-3780-43dd-bf6f-91c2242e10a2.html
html/74589de2-ef57-4840-9e01-ffb82286727b.html
html/8d9d826b-59e9-4774-ab2f-0d26597de393.html
html/e0ed203b-d6dc-4f0b-b00b-43608359c69c.html

Viviane7 8 23 2.1_OSXV2 TG

---

html/28363137-5337-40dd-a70d-ab54b6771119.html
html/2d9de6fc-11ba-45cc-929c-fc49cbf74a7e.html
html/40407688-4452-4539-9d0e-17754628b0b2.html
html/629a95ac-3780-43dd-bf6f-91c2242e10a2.html
html/6db941e2-e498-4b35-b31c-eab180364249.html
html/7d86624c-66e5-4160-91fe-eee23aa90d06.html
html/8d9d826b-59e9-4774-ab2f-0d26597de393.html
html/96732a05-1b58-45b0-bff0-09aeaf0bf3c3.html
html/b9caeea7-b3ee-42fd-81d1-1fc4f8d644a9.html
html/c635ad79-99e8-462b-9cb2-f6eaab10a515.html
html/e0ed203b-d6dc-4f0b-b00b-43608359c69c.html

Viviane7 8 23 2.1_OSXV2 Changes SE

---

html/21d09451-231d-4c4c-bc45-fff459ee968f.html
html/2abca732-354c-41fc-b1a5-cbce9001651a.html
html/58c03d8f-b99b-47b8-8c39-e67dc324223a.html
html/5f2664e3-e4f6-4bc3-a263-6f451ec00bfd.html
html/9ae7eb16-33d5-4fe3-8315-056b35ab93c8.html
html/b0a8d0e1-92ce-4410-b5f5-678bb8f36993.html
html/c840bec5-05ab-4baf-9a02-1b01aaffc34b.html
html/ced200a4-82d7-4098-b69e-f294ab578b3d.html
html/e3536a2c-7801-4bf7-8228-3c9ce8da6a11.html
html/f3e72252-6724-4cba-8843-9b51542ffaf4.html
html/fa1be41d-e770-4c99-8bdb-fccacbd81a6c.html

Viviane7 9 23 2.10_OSXV2 SE changes

---

html/5d15feaf-e487-4690-ac78-945ebd37bea1.html
html/f0145133-640f-4941-a134-c32b3cd37ffe.html
html/f73b7937-3b80-42d1-bbc7-6a7f68051a37.html

Viviane7 9 23 2.11_OSXV2 

---

html/1ce58775-5910-4d22-ad95-005021c7d142.html
html/66effaef-4c85-4eed-922c-a5def03ec7f2.html
html/90edb2f6-d955-4f30-ba0e-c172057fd175.html
html/a892b9a1-7467-45ce-a35e-a192a1befa0a.html
html/d7da75aa-655b-4168-bbb3-b73ed85fa4d0.html
html/de309d54-4f64-4c8e-aa22-9ab0a5fe98be.html

Viviane7 10 23 2.11_OSXV2TG Changes

---

html/08217b05-5c68-4ad1-9c60-dab706803f98.html
html/4747c17e-27e6-49e7-b4ec-e0230fe64b02.html
html/4e3d53b0-49c3-4269-8209-3fb49362af24.html
html/5e9e8262-b73a-415e-8e88-43607b655304.html
html/6c63f345-5519-42e9-9745-79e60eae63fd.html
html/703c3579-f40a-4ea8-9183-ab1e4c7f8064.html
html/7453e10f-1250-4dce-8eb5-82d9a052a052.html
html/8c343785-36de-4549-a3be-de0364540473.html
html/9adf0016-e1c6-4efb-b527-47a81b9ffd8d.html
html/a892b9a1-7467-45ce-a35e-a192a1befa0a.html
html/d36b08de-3fbb-4948-beb5-dba2ea95aaf6.html
html/d7da75aa-655b-4168-bbb3-b73ed85fa4d0.html
html/f0145133-640f-4941-a134-c32b3cd37ffe.html
html/f931c750-6f91-4854-b9be-5b94ebc9ef3d.html

Viviane7 10 23 1.15 (old 1.14) _SE changes

---

html/28363137-5337-40dd-a70d-ab54b6771119.html
html/629a95ac-3780-43dd-bf6f-91c2242e10a2.html
html/6db941e2-e498-4b35-b31c-eab180364249.html
html/74589de2-ef57-4840-9e01-ffb82286727b.html
html/7d86624c-66e5-4160-91fe-eee23aa90d06.html
html/8d9d826b-59e9-4774-ab2f-0d26597de393.html
html/96732a05-1b58-45b0-bff0-09aeaf0bf3c3.html
html/b9caeea7-b3ee-42fd-81d1-1fc4f8d644a9.html
html/c635ad79-99e8-462b-9cb2-f6eaab10a515.html
html/e0ed203b-d6dc-4f0b-b00b-43608359c69c.html

2.1 revisions 2.1_OSXV2Revisions

---

html/5bca3167-b9eb-4d74-9f08-edc180b29431.html
html/62068f7f-4bb6-4638-ab5c-e1c5a0790981.html
html/73faf22a-5d1f-49bf-9ab1-fb5d05d29bb8.html
html/b1604ec1-a906-4006-9e88-6f9cc3b24c54.html
html/c38f248c-675d-4b19-a888-075807107956.html
html/cdb9becc-9214-471a-847c-0ee6827b7da8.html

Viviane7 11 231.11_OSXV2 TG Changes

---

html/1b9100be-2004-4947-84ba-f44a5b5fc6a3.html
html/1efaa372-0796-4819-9161-d25f8350e651.html
html/388b9913-1eeb-4fd8-869e-c1d4434dc31a.html
html/47023f4c-88f9-4029-a99c-a98d17772b7b.html
html/4eeea81c-6424-4d4c-8f28-51aaa536d9ce.html
html/6023a5a0-8a56-4475-8b28-689cfcd423aa.html
html/91ba4f77-c324-40d7-80dc-ef2c16aa2181.html
html/966c996f-29ee-4f34-8e91-f9e9cdc6b62d.html
html/e37fa3cb-488e-4172-9b81-e72fbaddfdc7.html

Viviane7 12 231.8_OSXV2revisions

---

html/228e115e-3e86-40ff-aa5f-6adebc0b3fac.html
html/2bc126b6-d986-49e0-b098-2ca3f75d41eb.html
html/799b56e8-4abd-4efa-852f-71bea1c09e77.html
html/a3eb3c57-dc2b-4269-88c5-0a9adb18feb8.html

Viviane7 12 23 1.9_OSXV2revisions

---

html/2ee912c9-51d1-4dcd-b32c-0efa0fdcf7b5.html
html/478333eb-77e7-447b-875d-671aed9b7932.html
html/55eb311e-d2b9-46c1-a643-66eecb5282a2.html
html/73faf22a-5d1f-49bf-9ab1-fb5d05d29bb8.html
html/c38f248c-675d-4b19-a888-075807107956.html
html/c9696a71-9bae-49c5-8c53-7fd9bf7f28fd.html
html/dc7ca907-4ea6-4a31-ab35-38961db61376.html

Viviane7 12 23 1.11_OSXV2SEchanges

---

html/01e2057f-8163-4054-a113-b949180d2cdd.html
html/25acef07-cccd-4c04-ba31-c719071d41c9.html
html/51d4138a-85c8-4795-945a-e59b74f672b7.html
html/5cf6119f-ed3f-4b90-96e1-01549b6638a5.html
html/89896bb0-ec58-44e5-993f-8a5ac9f1457b.html
html/8f277699-8c14-437e-aa8a-320ed58d73db.html
html/eb628d16-e550-46c2-9a15-545c8d7d1073.html
html/f5a0b3a4-8d24-4626-8ef2-5692618a30a4.html

Viviane7 12 23 1.12_OSXV2 TG changes

---

html/1fd302d8-2043-4833-945b-0f4e0a4892e6.html
html/3107b4b5-170a-4fc4-bc4f-dee2caa0e850.html
html/858f4188-2f31-4dca-8923-9d0e6d69037a.html
html/a1d98125-0fba-4dc3-9f1c-c45332e91545.html
html/a2424502-8f9a-47f7-a7c3-400c3d86cc23.html
html/a3199718-cc11-43b3-baec-9cac85d47340.html
html/b3a51d93-8faf-400b-bfb1-b6c7bc38d169.html
html/d013660f-3672-434e-8c03-4779aa577260.html
html/d187ace0-92df-4d92-b9fa-853c8667830b.html
html/f1cd85df-9fbb-4dd1-9d86-8355f28cb47b.html

Viviane7 13 23 3.1_OSXV2SE

---

html/25dcbc78-5cd4-46ce-b77c-57a57fc89375.html
html/4bb1b387-6324-4cbd-a36d-93860e467540.html
html/50354c79-7450-4765-8723-f4f24754142c.html
html/8190d71e-aaba-4b37-9003-7b04296df919.html

Viviane7 15 23 2.3_OSXV2 TG

---

html/20b661ca-df9b-462e-bdf1-4235a49b33fb.html
html/4bb1b387-6324-4cbd-a36d-93860e467540.html
html/5ebc9c1a-720e-4ade-afd2-9f62537f43ca.html
html/9e0dc292-d786-4f6a-9a93-b21f60ff1915.html
html/9f8c9114-b35d-4012-95a3-b8d837c8e2ad.html
html/cb3d7a71-983e-4b4c-9523-e053ec8ce062.html
html/f4441e3d-ca35-4b20-9fdd-aaf5bc3b634b.html
html/f6adfaf1-d357-45d5-8c0d-5eab5beed536.html

Viviane7 15 23 2.3_OSXV2SE

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html
html/04cbe2bf-e9f8-47d5-bca8-4fc6577d75d1.html
html/ba648cae-9497-4249-b70d-151c61d8914f.html
html/c64e158e-7168-4438-bd16-565adeeb87fd.html

Viviane7 15 23 Unit1_OSXV2 

---

html/1a4e8548-2a1a-4611-b603-d958ef7b9394.html
html/25ed3bfa-ab94-416a-bfb3-65582b3e5235.html
html/3a8e40f2-e09d-48e7-b84a-edbf2bfc743e.html
html/3c70e45d-be83-4224-ac86-61cc4551a825.html
html/3fde002b-bf85-4007-a396-6a59041e56df.html
html/46245976-a55c-4160-9741-66021e3e45ee.html
html/4630f2be-00aa-4cf8-a231-1a4728897166.html
html/4b905552-e7ca-4c65-bc82-bdba97e71772.html
html/4ebb1fa2-0be4-4f16-a6b9-e1d03847a1cd.html
html/5e69f4ad-cd83-4f36-b4a5-a4c1563c384f.html
html/7b0f6075-e3cc-4f3d-ad37-454862277bd8.html
html/9469bdb7-c10e-4381-ad09-c3ad374859ff.html
html/9b75f40a-0ed3-4bff-a8bb-857d379213a4.html
html/9d3a3ac2-3766-4254-94f0-39d98232e1bf.html
html/afe9280f-4e52-408f-a585-3e9521226e6a.html
html/c6052dc3-8d5f-4db4-83f9-b3348d20e0fc.html
html/c95d001e-3f53-479a-aeb1-68493f8a4b2b.html
html/cdd1f599-5765-45b1-978a-5f4a086143bf.html
html/ded25b85-676f-463d-9cb5-a398633c4919.html
html/df9bfb6c-a792-4f39-9122-226b5071e02c.html
html/ee0baed5-b6c3-4844-95f3-5dd02ad727a4.html
html/fc299aaf-71bc-4f81-a3b2-efc6d4a187bd.html

Lishazavala17

---

html/15c17242-46fd-4ad5-8739-8e2c335f5bf4.html
html/34b04d10-5f80-4628-8e93-711e4d9bc250.html
html/6413d708-9522-4476-82e6-db16d09590c8.html
html/727e7e42-25aa-46a5-8b11-1ecd7ce05dd6.html
html/8bceb00e-777b-4e09-9f24-b3a47ddf92a8.html
html/d73f0137-f866-4dda-9149-282ad1af7342.html
html/e44ec8ee-ac66-4cfc-891c-110cfac52b10.html
html/ebc9ce5a-0de2-4e4e-8c78-5ddb08783df7.html

Viviane7 16 23 2.4_OSXV2 TG

---

html/1b73ef16-e512-45fc-bc61-efeadda28af6.html
html/4a7c39ee-0b0a-4968-8ed4-d3fe91c31017.html
html/8d1b6a8f-e23b-4e78-bd2f-909aef45a997.html
html/bb5c6635-2dd5-4979-94f0-b71a9cbcafb9.html
html/bbe9e341-8c24-4a71-9dde-b73679daf8b8.html
html/c7a8fadf-fc81-409f-b25f-20cfb06de37f.html
html/eae2583f-4745-43c2-a9e9-99d93f5bcb1c.html

Viviane7 16 23 2.7_OSXV2 TG

---

html/1de9033c-452d-4d6c-825b-2a894b0079bc.html
html/56cd8640-3a8e-43fc-9c78-832548e67586.html
html/6778a5eb-397e-44db-8c4d-b8526261973b.html
html/8c9a833d-eb31-4fdb-9d19-cb579fcb38a9.html
html/91dad32a-3446-4da3-b347-a19ef2db6126.html
html/bbe9e341-8c24-4a71-9dde-b73679daf8b8.html
html/e26ce928-d4df-47bb-8bbc-dd5f2d2320e9.html
html/ef4f8d97-cf47-4332-934e-860ded4de341.html
html/fff9877b-c259-475f-a2d3-95cee4ba4a19.html

Viviane7 16 23 2.7_OSXV2SE

---

html/e6ffbebd-c045-4802-a4d0-68450c7533ca.html

Fixed the following issue:
"In the feedback for Q2, delete the second instance of “is” from the last bullet."

2.3.1-se-feedback-edit

---

html/0cb1d34a-12c8-40f8-b6d6-bc80d24f1186.html
html/3b5616a7-c41f-44a6-86ef-db20627e0a5d.html
html/3d042d75-f62c-45e4-8a9a-f2d3bea902c4.html
html/5e259f34-88a4-4859-bcd5-88eb1376fa44.html
html/827e8a62-6a54-4f03-86f8-44d04554d657.html
html/91aa4085-a50e-4221-856f-01af984fd722.html
html/be3cb8b6-1154-48ab-964b-eb8609c9aee0.html
html/d81cda25-c5fa-4d8e-8c2f-6043b2b8edff.html
html/eb7e43bf-a0c5-4f7c-9f90-b391a76c3a4f.html
html/f0d01799-5016-4553-ab35-eb694155b60b.html

Viviane7 17 23 1.1_OSXV2SE

---

html/ebf14197-5921-4b0b-978f-80b3138ceab5.html

Q11: changed feedback from "x=12" to "x=1/2" (using KaTeX)

TG-2.3.2-Q11-feedback

---

html/20b661ca-df9b-462e-bdf1-4235a49b33fb.html

deleted one space from each of the last two lines in the equation below "We can add the equations, so 𝑠 will be eliminated when we add these two equations."

2.3.2-SE-alignment-edit

---

html/20b661ca-df9b-462e-bdf1-4235a49b33fb.html

Attempt to align to equals sign

TG-2.3.2-alignment-edits (2)

---

html/31245ba3-79d6-4f65-a249-bd797ad6cb1e.html
html/376a56c1-d2bc-414a-9a22-056ee3bf1457.html
html/3dc2a917-7c8b-46fd-b6c1-0bd0d2695b3b.html
html/645713c9-4b8b-47b0-b3bb-0e2e1697dcc6.html
html/6f773776-626c-4cda-ab88-ea02e2f093f0.html
html/92ccfb8c-2c63-475b-bd46-c27bc5436301.html
html/a6f3e5e9-0c2a-4f5b-96e2-268b402f81fd.html
html/bf8db043-6926-45ec-bb48-509077639e32.html
html/c19e46cd-0cf7-410a-91b7-a01cbf03c894.html
html/e0d958d4-ea6c-4fc5-850d-3544b0e2d582.html
html/e8c49e80-af6a-4a6c-bbdb-e1d1855b485b.html
html/f4e0ce89-c669-49fc-bb7d-c5a0ee7f6be2.html
html/fc1661f6-7bff-493d-ad4b-b04e3973deba.html

Lishazavala18

---

html/9602a148-bee4-472d-9373-4ee33b2e2b3a.html
html/987a9303-dddd-4a68-85b6-16ee5fd4f785.html
html/c7292a8c-40af-4c74-bf59-a00394e86628.html

Lishazavala20

---

html/a9067bb2-27c2-4140-9c94-a562f2ab0adc.html

5.9.3TG question update

---

html/8249127e-742a-4d82-8a91-e7333781df4c.html

5.9.3SE validation fix

---

html/183a0c24-1f11-4135-809a-342a9999bbfd.html
html/261b60c4-370d-4027-a6ed-3f982dd735cc.html

5.8.2 and 5.8.3SE changes done

---

html/79cda3ad-e022-4f67-aa74-264d2a022f48.html

5.8.3TG activity changes

---

html/5873e1a1-ee03-467d-9ff9-1f93ba3ca1f0.html
html/79cda3ad-e022-4f67-aa74-264d2a022f48.html

5.8.5TG changes done

---

html/5873e1a1-ee03-467d-9ff9-1f93ba3ca1f0.html
html/ed698135-431e-4649-a9dc-b5fe75918903.html

5.8.5SE changes done

---

html/546bd09e-e722-4393-94c2-0108093cf1e6.html
html/ef3c9aa1-f939-4c87-81ac-e46b8db0a269.html

5.8 changes done

---

html/8694124c-7bfd-4968-bfe6-864dbf69018c.html
html/8a244aff-9671-40e7-9090-b3a7686712af.html

5.5.3TG and SE new problems

---

html/3d042d75-f62c-45e4-8a9a-f2d3bea902c4.html

Emergency Change for Alyssa before her instructional

Change 1.1.5 questions 9 and 10

---

html/026a024d-dd99-485c-b670-446a3b8156a3.html
html/ce79f532-acc7-47aa-9918-0ebb97002d31.html

2.12.4   NEW 2.13.4

---

html/038da545-167a-4011-b611-d433043ad412.html
html/4c18086f-40b4-46d3-a662-47fff955ec2b.html
html/86dfe56c-cc01-4d6a-b6e1-8f680ab2748f.html
html/9e617b29-706b-4f9d-b0fb-207e30c62d81.html
html/c9aa0e69-e024-4f8a-b9cc-dc29b5c5009f.html
html/e8cda69f-0414-473a-bdc5-955d472a9b43.html

Lishazavala26

---

authoring/scripts/inject_additional_html.sh

I'm creating this PR so it's staged and ready to go but will wait to merge until the corresponding code has cleared QA in staging.

Update auth environment code versions

---

html/091fcb81-2b93-448d-8bd2-fb3173250d18.html
html/21376953-5c77-4992-bc71-e6d24f9bec8e.html
html/28363137-5337-40dd-a70d-ab54b6771119.html
html/38efa412-68f0-4b46-8f28-2e7d75955d94.html
html/4b6b1a1c-234d-44ba-88e5-fe6b05e7d805.html
html/7c65f069-f005-4936-824f-f53bb20b46f9.html
html/7e1f0dbd-8ae4-4114-923e-ee02e2fa54bf.html
html/c6a0f7c1-6e84-49ff-b6b0-3f7b1de9d9d8.html
html/e9b16c51-82db-43de-9882-7023bd00f303.html
html/ef7860ea-b0f9-405c-8a59-ac4c79ca3767.html
html/fa1be41d-e770-4c99-8bdb-fccacbd81a6c.html

ignore branch names:
2.1.5 EE added to ONE question and others are corrected to be STUDENT side questions. To TEST it out.
1-4.16 practice questions corrected from audit. NOT DONE YET.

Addcomptoquestions1

---

html/0741815b-19b3-476a-ac2d-4b0d13f99253.html
html/1caaf78e-ca6d-4aff-ad7c-47d87d426b7b.html
html/2fb9004a-ced9-4179-948b-70c7489af28b.html
html/57ff8e29-131b-4df4-8fb1-7913798397e5.html
html/641bae29-d837-4241-896f-4432a451f37b.html
html/69a7a75c-1d34-42a5-a90d-89600018b359.html
html/858c6ac4-78e7-482f-a6c0-c3c618d8aca3.html
html/87055a31-6dce-4fab-bd62-8d993984d4e5.html
html/8e91d2ba-d978-4808-a03a-ba4da71e1678.html
html/a7c944f7-7aa6-4a91-9a7b-3cc2e253dde2.html
html/f4e0ce89-c669-49fc-bb7d-c5a0ee7f6be2.html

Practice question audits high priority ones are done now. STILL need AH to check the remaining errata before I can consider this task finished. 
This means there will be more practice question edits trickled into the next push with EE edits. FYI

Practicequestionsand ee1

---

html/07d86811-f0bc-4bb2-be81-faf2e93d9d12.html
html/11645ad3-fa32-4a64-89ec-d53bb0be4a61.html
html/1640b62e-8cc2-4029-8da8-2b31a8b756b5.html
html/630661d7-786d-4f13-b1d8-a7d8ce7cf8cd.html
html/656a08a0-d01c-488e-91e1-da78d33a01f2.html
html/9868762f-4882-4669-8112-2d7099214674.html
html/b7b3b402-1e20-4e77-97e3-c66f50d49c50.html
html/c6a0f7c1-6e84-49ff-b6b0-3f7b1de9d9d8.html
html/dc7ca907-4ea6-4a31-ab35-38961db61376.html

one urgent correction in the first commit (found by maddy)
first stab of doing EE additions (NOT DONE YET)

Practicequestionsand ee2

---

html/630661d7-786d-4f13-b1d8-a7d8ce7cf8cd.html
html/9d6f3ea5-d97e-470c-8b6e-582b6204d878.html
html/c6a0f7c1-6e84-49ff-b6b0-3f7b1de9d9d8.html

branch name is irrelevant there. This is reverse change to some EE additions 😭

undid some EE additions because EE not support INEQUALITIES *SAD FACE*

---

html/01a72df3-a600-4f47-b3d0-eeaee7c689de.html
html/030ae31f-c3ab-4645-9770-89a76206876d.html
html/0dbff3c2-3791-4f01-98d6-5c9f8224179d.html
html/124a6012-1bfd-4a91-867c-bbc0e03d158f.html
html/2a79904c-bbfa-4635-a51d-9ff7b8d87b1a.html
html/2d638253-5726-4d9c-925a-830f69a3d6a2.html
html/2ffa9df4-dd45-4847-9c5d-066d333795e9.html
html/3978b112-ec32-4078-88b9-87a397311a7f.html
html/41c06865-85de-4faf-9b19-44865f5b0b5e.html
html/4f633a41-6184-4b48-9004-65c95b5681e7.html
html/5c76dbe6-107b-4b99-80d0-faa41127c89c.html
html/73fbce4c-a86a-4ef5-8bdb-b006b282ec5e.html
html/749ba7c1-2617-4997-9c6e-b86b476bac6c.html
html/80bab9fc-149d-426a-acde-9433d4dadf75.html
html/86dfe56c-cc01-4d6a-b6e1-8f680ab2748f.html
html/8f9d899d-c04a-448f-aa91-7431b264f001.html
html/9c0e05a2-4481-4e97-8081-77753f9aebb1.html
html/bed2702a-600e-4d62-82b5-68ad1644ccf1.html
html/c0b57151-848d-4623-b902-bb30718f5f5a.html
html/d022800d-b439-41f7-9090-aad65e87360b.html
html/d11f0413-114d-48db-9d75-87ed4620fc16.html
html/f25f0afa-6a1a-4794-ba10-4571d7a61f5c.html

MLR 1-8 added with no Graphic organizer
MLR, SWD and ELL put in extra support and separated

all mlr complete

---

html/07d86811-f0bc-4bb2-be81-faf2e93d9d12.html
html/0e917220-f905-4ae0-a004-e827a916bab5.html
html/1640b62e-8cc2-4029-8da8-2b31a8b756b5.html
html/7edde188-0d58-4ae8-a64e-c47140551c4a.html
html/857a8f48-e36a-445b-b307-a0d083ee1785.html
html/9b1f7792-4a4e-4f80-952a-2281188930f5.html
html/b7b3b402-1e20-4e77-97e3-c66f50d49c50.html
html/c6a0f7c1-6e84-49ff-b6b0-3f7b1de9d9d8.html
html/cdb9becc-9214-471a-847c-0ee6827b7da8.html
html/cecc7da7-9c40-4efd-8234-35cbe4dabb46.html
html/dc7ca907-4ea6-4a31-ab35-38961db61376.html
html/f5a0b3a4-8d24-4626-8ef2-5692618a30a4.html

Undid files with 4+ changes to EE from multiple choice so that we can turn AH selection of 2 questions into EE only

UNDO_EEsecondround2

---

html/1d6860c9-6536-4d6c-bb40-4034a218ec07.html
html/66effaef-4c85-4eed-922c-a5def03ec7f2.html
html/9e749b17-0286-48dd-b1b8-50d6c898bfea.html
html/c73e2112-12bf-4973-aa90-92d81b5750a7.html
html/d19dd780-7b98-4dcd-8f0e-050fbd57532a.html
html/d3f586ec-b240-4579-ace1-ffe865fa9bbd.html
html/f89e0577-e09a-4abd-a8ca-671d2df38749.html

Fixed some spacing and formatting / cosmetic on teacher overview pages.

fixed spacing and remove extra gray boxes from all teacher overview pages

---

html/1640b62e-8cc2-4029-8da8-2b31a8b756b5.html
html/7edde188-0d58-4ae8-a64e-c47140551c4a.html
html/9868762f-4882-4669-8112-2d7099214674.html
html/cdb9becc-9214-471a-847c-0ee6827b7da8.html
html/dc7ca907-4ea6-4a31-ab35-38961db61376.html

small changes just pushing so i can update the TOC

E eundopart6

---

html/1dc8dc80-3244-481b-a7db-e5ff4803c43e.html

FSM recreated with mockup unit 2

fsm unit 2

---

html/fd1fb70c-8732-4afd-91eb-ca89279805f0.html

Tweak for the Sample Submission

Fix 9.2.3 Teacher Guide Formatting

---

html/2dd5bbad-9cf2-4cf9-8866-158cabf9243f.html

fsm 3 corrected

---

html/2dd5bbad-9cf2-4cf9-8866-158cabf9243f.html

fsm 3 round 3 changes'

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html

unit 1 accordian test

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html
html/2193951b-1729-4217-8a99-d2914652fc0b.html
html/344fa2bb-0651-4a6f-a28f-c368b8896060.html
html/3bc8d9d3-75ef-45ca-9b0e-a90e9532df35.html
html/7346fb12-a440-4647-a8ce-026b667a5fd4.html
html/8617b423-741d-423a-bdf5-45f419e680e9.html
html/b9e2cc0a-8abd-40b3-8026-8bd5314bfe40.html
html/c1da77f3-dfa5-4d4d-b5f7-61e4a683e30f.html
html/e5a137d7-f628-4b71-83bf-679260acf9d6.html

accordion unit 1 finished

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html
html/149e5d4f-3e57-4642-9b4c-56850081fab4.html
html/b9e2cc0a-8abd-40b3-8026-8bd5314bfe40.html

Accordian redo

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html
html/2193951b-1729-4217-8a99-d2914652fc0b.html
html/344fa2bb-0651-4a6f-a28f-c368b8896060.html
html/3bc8d9d3-75ef-45ca-9b0e-a90e9532df35.html
html/7346fb12-a440-4647-a8ce-026b667a5fd4.html
html/8617b423-741d-423a-bdf5-45f419e680e9.html
html/b9e2cc0a-8abd-40b3-8026-8bd5314bfe40.html
html/c1da77f3-dfa5-4d4d-b5f7-61e4a683e30f.html
html/e5a137d7-f628-4b71-83bf-679260acf9d6.html

overview and readiness in all units now have accordions

done with accordian in overview all units

---

.github/CODEOWNERS

Reverts openstax/k12-contents-raise#1536

Revert "Add CODEOWNERS file"

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html
html/2193951b-1729-4217-8a99-d2914652fc0b.html
html/344fa2bb-0651-4a6f-a28f-c368b8896060.html
html/3bc8d9d3-75ef-45ca-9b0e-a90e9532df35.html
html/7346fb12-a440-4647-a8ce-026b667a5fd4.html
html/8617b423-741d-423a-bdf5-45f419e680e9.html
html/b9e2cc0a-8abd-40b3-8026-8bd5314bfe40.html
html/c1da77f3-dfa5-4d4d-b5f7-61e4a683e30f.html
html/e5a137d7-f628-4b71-83bf-679260acf9d6.html

teks text doublespaced in all overview units

teks text doublespaced in all overview units

---

html/020533d8-ba31-49bb-83a1-e96a37c23c7b.html
html/73faf22a-5d1f-49bf-9ab1-fb5d05d29bb8.html
html/b9e2cc0a-8abd-40b3-8026-8bd5314bfe40.html

accordion typo corrected

---

html/05a02a4b-73e7-49d9-9375-5f1050612a7b.html
html/0fe2ebb0-0122-49ca-8981-41ee365862d9.html
html/11131447-b0a8-4075-8a7f-fab69098a4f4.html
html/1b8d1c95-5f8a-478c-aec2-315d3608d2ac.html
html/2d0c2c2d-aa56-49f6-9238-a367299dc2e3.html
html/325ea039-905d-43b7-b34e-16b026d2c3c9.html
html/4c71d1a7-c980-4e61-a6fa-5f38802635a1.html
html/4dbe1dd7-693e-49b0-9379-e14c50b59ec6.html
html/6455920d-9270-4c96-8bab-7164d9754fab.html
html/73552909-ce34-4456-b15a-3fdcf8a18447.html
html/735553fb-3753-4a44-b164-aa454bca72fe.html
html/7cce28be-76bf-4030-a44a-839e68db4f5e.html
html/85b15ef8-da43-4486-b78c-dbf7b8786307.html
html/8aff1570-1b82-45c1-9b87-70d6bbd0c4b2.html
html/9b5460ca-935e-45a6-aece-f3e42b3565d3.html
html/aa2c59ff-2503-4011-b3ee-5750820539df.html
html/ab3d96c3-f3f8-4df0-8544-7b849787def6.html
html/afbaa505-5cb6-4f02-ac5f-62e297b7824f.html
html/ba6502ca-26f7-4cd4-800a-c8af8ed811d2.html
html/c331c42e-f506-4f35-9e75-cd9d83e34933.html
html/c78483bb-df6d-4985-9c3e-5bedbcdb0a62.html
html/e3050640-f992-4bb2-897e-f13b8e646f64.html
html/e408d781-2d31-40f4-a489-b69840c4b917.html
html/f802bc8a-ffdf-4fbe-b123-07c272247571.html
html/fb149f8d-7732-479f-ad40-e35454e4899b.html

projects qa and double header remove

---

html/0151560d-a4ab-4859-9b31-ef8d060fe9b2.html
html/842407ca-3e1a-4812-b12b-1e77c7d324e6.html

just kidding this is the last imra push :)

tg 4.11.4 done

---

html/0151560d-a4ab-4859-9b31-ef8d060fe9b2.html
html/842407ca-3e1a-4812-b12b-1e77c7d324e6.html

kidding again this is the last one

fix tg for 4.11.2 & 4 add mlr

---

html/7853fa11-5d78-4422-83b0-207ac4330026.html

unit 4.12 edits: ID B-3161-U3-SWD and B-3163-U4-ELL

unit 4.12 edits: ID B-3161-U3-SWD and B-3163-U4-ELL

---

html/67791ab5-75fc-4cd1-8dbc-03bf9147a897.html
html/69055bd4-81f6-4b12-91f5-03005d6b4fc4.html
html/842407ca-3e1a-4812-b12b-1e77c7d324e6.html
html/96870bbf-6b67-4dda-a571-57466240f356.html
html/b7425e63-bb3f-4f8b-a3b3-bd076407ed95.html
html/ee30b4dc-2278-40b8-bfc7-830e7c775c0d.html
html/f422c30b-cb5b-4c95-9862-41acc10866f6.html

B-3166--SWD B-3170-U4-ELL B-3171-U4-SWD B-3172-U4-SWD B-3174-U4-SWD B-3182-U4-SWD B-3183-U4-ELL B-3184-U4-SWD

B-3166--SWD B-3170-U4-ELL B-3171-U4-SWD B-3172-U4-SWD B-3174-U4-SWD B-3182-U4-SWD B-3183-U4-ELL B-3184-U4-SWD

---

html/07c539b4-2f56-4bfc-8ca4-fad2f7ee620f.html
html/111cfe12-3302-47e7-89c3-9bc58877cbee.html
html/7be54f29-3ed2-436c-a8a1-05804e43e51c.html
html/859f0953-9245-4c8c-9168-46ded13d15b0.html
html/e14b3c4c-857d-4d0f-85e8-95fd74ad4614.html

B-3185-U4-SWD
B-3186-U4-ELL
B-3187-U4-SWD
B-3188-U4-ELL
B-3189-U4-ELL
B-3190-U4-SWD
B-3191-U4-ELL
B-3192-U4-SWD

B-3185-U4-SWD B-3186-U4-ELL B-3187-U4-SWD B-3188-U4-ELL B-3189-U4-ELL B-3190-U4-SWD B-3191-U4-ELL B-3192-U4-SWD

---

html/0151560d-a4ab-4859-9b31-ef8d060fe9b2.html
html/8151d66a-f79c-4031-9ba4-1a4dbf041f9a.html
html/842407ca-3e1a-4812-b12b-1e77c7d324e6.html
html/aba06993-6f5b-4bba-9098-851b59d063d5.html
html/aec423ce-4269-4ce6-809f-d7c0c9558754.html
html/ba8bdd23-335f-4c02-b0c2-fe5c1456b4ce.html
html/c85320f3-e717-4607-99bf-5420380fc4f3.html
html/e902ad49-1e26-424d-9604-6aa297484919.html
html/e93a5fb9-54ef-4216-bb4e-4f05ee053f41.html

B-4162-U4-CNV
B-4163-U4-CON
B-4164-U4-CNV
B-4025-U4-CON
B-4169-U4-CNV
B-4165-U4-CON
B-3193-U4-SWD
B-4170-U4-CNV
B-4167-U4-CNV

Smartsheetstar4pt8

---

html/0151560d-a4ab-4859-9b31-ef8d060fe9b2.html
html/aec423ce-4269-4ce6-809f-d7c0c9558754.html
html/dcb3267b-443d-4f5c-897e-1b89e70b7dcc.html

"B-4166-U4-CON"
"B-4171-U4-CON"
"B-4168-U4-CNV"

4.18 last changes

---

html/0151560d-a4ab-4859-9b31-ef8d060fe9b2.html
html/aec423ce-4269-4ce6-809f-d7c0c9558754.html
html/dcb3267b-443d-4f5c-897e-1b89e70b7dcc.html

additions to "B-4166-U4-CON"
"B-4171-U4-CON"
"B-4168-U4-CNV"

Smartsheetstar4pt13

---

html/8dbf8797-126e-47c7-8fdc-fc0a45a301f5.html
html/bff2fe03-f055-475a-9b89-11c859d2a115.html
html/e40ef55a-a005-460f-bce3-bcef3cfc0d37.html

Part of mbz change to add buckets

inquiry projects added unit 4 and 6

---

html/084876da-09d6-4e78-ae36-5aaabc730547.html
html/11c39a8d-798b-4d05-b808-bc30217c4bd3.html
html/22ec3ab5-42cd-43d2-b773-19d2a3f39e17.html
html/9695369c-6554-4d3a-88ab-7617d675c9f7.html
html/e9bde82a-143f-4d72-8462-77455bd7f43b.html
html/f0c199d1-c39e-41f6-841d-7ab94f677d27.html

and "B-4037-U1-Code" & "B-4038-U1-Code" & "B-4208-U1-CON"

B-4210-U4-CNV student only

---

html/4e83d521-f2c6-40e3-8994-14054cf02a2e.html
html/7779b9ac-0b06-42f7-8f60-023b0124d6fb.html
html/8e390488-6833-422a-acba-23e6cc6f169e.html
html/afb3f309-da04-4a26-9162-74d8c7525d3d.html
html/c3561bea-b1fd-4282-8755-405857bb6403.html
html/e0dcd1fd-8ac8-4a98-beef-a2c4f936ffbd.html
html/fcf37686-b537-43f1-8ac8-ef85b5a059be.html
html/fefcd7c1-efe4-49ec-b235-7d2736203d0d.html

"B-4215-
U7-CON"
"B-4216-
U7-CON"
"B-4209-
U7-CON"
"B-4210-
U7-CON"
"B-4211-
U7-CON"
"B-4212-
U7-CON"
"B-4213-
U7-CON"
"B-4214-
U7-CON"

see description

---

html/11c39a8d-798b-4d05-b808-bc30217c4bd3.html
html/4c18086f-40b4-46d3-a662-47fff955ec2b.html
html/9b5460ca-935e-45a6-aece-f3e42b3565d3.html
html/afb3f309-da04-4a26-9162-74d8c7525d3d.html
html/b68d9c6f-a76b-4b6e-827b-e5ff63a9d980.html
html/c3f85c53-0cb4-4295-8487-aa0e8386c227.html
html/d2662d14-0c1a-48dd-891f-66bf4b7d5a7e.html
html/d483b99c-8f41-484c-839a-7ecd35cb0d11.html
html/e408d781-2d31-40f4-a489-b69840c4b917.html
html/ec9f0bb1-37c1-4ed5-baf5-9eea082b1be1.html
html/f0c199d1-c39e-41f6-841d-7ab94f677d27.html

"B-4210-U4-CNV" for U4 Inquiry Project page
"B-4210-U6-CNV" for U6 Inquiry Project page

Btspriorityaugend2

---

html/07fef9d8-6c68-40d7-8402-043b1ad92fba.html
html/11645ad3-fa32-4a64-89ec-d53bb0be4a61.html
html/22942bee-9c0b-4778-8d8b-4ae494e650f6.html
html/388b9913-1eeb-4fd8-869e-c1d4434dc31a.html
html/3fe4677c-6279-45fd-b93c-da41b8b20514.html
html/47023f4c-88f9-4029-a99c-a98d17772b7b.html
html/5cf6119f-ed3f-4b90-96e1-01549b6638a5.html
html/5f7b5898-364f-4e8d-be69-367de678ca25.html
html/60775a99-585a-4d8e-af06-2dafa58ec6fa.html
html/656a08a0-d01c-488e-91e1-da78d33a01f2.html
html/8228eb3c-e400-4094-a0f0-e60640d8cc27.html
html/8c7e108f-3df0-4812-907c-9fb01ac26965.html
html/b2769457-d920-4278-a885-71f067a48dfa.html
html/be3cb8b6-1154-48ab-964b-eb8609c9aee0.html
html/c4f92f86-91e4-4338-8723-92352e3b3d1b.html
html/c7c6adb4-28f4-4188-a560-3b890f25a8f8.html
html/ca423271-63c5-482c-bd1b-8a622d1cc20c.html
html/d2d045ba-1410-4709-bc61-dc1bd1e88e46.html
html/e0df4ff5-5b28-44d9-bbd6-43a704b94fe4.html
html/e14b3c4c-857d-4d0f-85e8-95fd74ad4614.html
html/e2040942-c588-49ec-912c-bfb7aa14a5ec.html
html/ee28ba3b-9598-4b80-b6ce-9d7c361f18bb.html

"B-4321-U6-UX"	AH	Unit 6 Project			SE, TG

project 6 and desmos user styling "B-4321-U6-UX"

---

html/11131447-b0a8-4075-8a7f-fab69098a4f4.html
html/2724bfba-1483-4075-aeff-9cc6085ddc17.html
html/2a2910de-e106-403c-8e6a-105d4eb7b6f7.html
html/480ee58d-c117-411d-be58-9ac70ca4045f.html
html/4dbe1dd7-693e-49b0-9379-e14c50b59ec6.html
html/5d87b49d-ab8c-4f00-943e-03874bbaa27d.html
html/7cce28be-76bf-4030-a44a-839e68db4f5e.html
html/b713138d-315b-459c-b4e4-aabd9882b10d.html
html/c444dfed-197c-4de6-b23a-2a6d02770ed1.html
html/c78483bb-df6d-4985-9c3e-5bedbcdb0a62.html
html/d42f14c9-e7f5-42ab-a6d3-f7e6dacfff66.html
html/ff94c93c-2f8b-4a5e-bfd5-72037103853a.html

projects 3 and 4 "B-4325-U3-UX" "B-4326-U4-UX"

Btspriorityaugend9

---

html/096a4469-5cd8-4786-9a7c-b59febaa2e73.html
html/35c7c190-d131-4f32-b67e-0bfac6341ae7.html
html/3dc9550c-44e3-46a9-bdae-27ef6f9e0b03.html
html/5d0f5c89-4b42-4b16-9025-5c50ff3ec1ae.html
html/9e62a9ad-a1ee-468a-a834-c0ac2de70388.html
html/cbad4720-d3ee-4374-94f9-706bb08ec811.html
html/e6f602e6-66b3-436d-8b9a-655dfe988523.html

Btspriorityaugend10 "B-4328-U5-UX"

---

html/70602e6b-7dea-432a-bdac-8077e6973303.html

added link so devs can add to the list to unblock

need polypad link to be added by devs to unblock me

---

html/1ab548d6-346a-4478-a9a3-5f77d0e02871.html
html/2e06a213-c141-41cc-92e0-853bd398c46f.html
html/33f9d858-d7ed-458d-9e19-d293a9ce66b2.html
html/cb7ec813-db50-4d78-8bce-6844c6b7b67d.html

"B-4308-U7-CON"TG-SE, "B-4309- U7-CON"_TG-SE

---

html/0cddef22-5aeb-4225-94ba-97de42a6b4fa.html
html/1c09713d-c71b-48e0-8e47-89ee36a77712.html
html/1fd302d8-2043-4833-945b-0f4e0a4892e6.html
html/21d09451-231d-4c4c-bc45-fff459ee968f.html
html/2659adfb-00ad-44ac-9082-cae39c674a93.html
html/2659adfb-00ad-44ac-9082-cae39c674a93/mm.html
html/28363137-5337-40dd-a70d-ab54b6771119.html
html/2e06a213-c141-41cc-92e0-853bd398c46f.html
html/4353e3d9-e2d8-4b5e-a9af-d3be4257c7fc.html
html/48047ea6-a869-4d25-a251-f12e5d83c24d.html
html/741fe3a3-c16a-4969-8705-14c953044bd3.html
html/9469bdb7-c10e-4381-ad09-c3ad374859ff.html
html/9bd3f379-663b-47bc-8d0e-29d0db603b1f.html
html/9f8c9114-b35d-4012-95a3-b8d837c8e2ad.html
html/a1d5d610-4fc6-404b-876e-a52d8986437e.html
html/a1d5d610-4fc6-404b-876e-a52d8986437e/mm.html
html/a4304b57-a601-4ad8-9306-240c9c4cf25d.html
html/b035845f-9d14-468e-a75c-8fbd573cc434.html
html/b4a4263b-057e-4141-b78e-6dc02178d5dd.html
html/c7a3b34a-96e4-4b80-ad04-1022ad0dbbeb.html
html/c840bec5-05ab-4baf-9a02-1b01aaffc34b.html
html/ed26bb59-758d-4069-bdaa-fae9751e4e51.html
html/efcd3bd0-d02e-4436-8f40-d86b26f5cb81.html

in pages with 3 or more desmos questions we embed usermessage w pdf link

student usermessage desmos select areas

---

html/060a3562-363b-4a6c-a4fc-870489e3bace.html
html/1d60507b-818a-402e-8c1c-99e3a59caf4b.html
html/34fefff8-4103-4c58-9047-51109416250e.html
html/4e64322f-b721-4f7a-b7c2-263dd03dd95c.html
html/5bb6e2e1-06e1-448e-a70b-ad35acd779a1.html
html/9e617b29-706b-4f9d-b0fb-207e30c62d81.html
html/b139f006-df8b-4e16-8068-6762d95d371e/anilocam-a.html
html/b139f006-df8b-4e16-8068-6762d95d371e/anilocam-b.html
html/biocidinplan.md
html/cc98afef-8ec5-45b7-a3f2-955512400b3c.html
html/d075f2e3-9a15-4d28-b0c7-484adce628d4.html
html/d075f2e3-9a15-4d28-b0c7-484adce628d4/anilocam-a.html
html/d075f2e3-9a15-4d28-b0c7-484adce628d4/anilocam-b.html
html/dca45446-7172-4719-8b84-11fe7a9d61e5.html
html/e6bc25e9-1fee-4aff-bb51-ba4b2f64fdab.html
html/f3ecf8dc-03e3-43fc-8dd8-fe0e2c16399f.html

important to push this one to the real course because there was a bug in pset questions not working.

pset bug removed

---

html/3107b4b5-170a-4fc4-bc4f-dee2caa0e850.html
html/5e69f4ad-cd83-4f36-b4a5-a4c1563c384f.html
html/63c7361e-8889-4878-b491-c16f9a791695.html
html/8f277699-8c14-437e-aa8a-320ed58d73db.html
html/93417e34-e4ad-4240-8c67-f35fe01eb773.html
html/9d3a3ac2-3766-4254-94f0-39d98232e1bf.html
html/a1d98125-0fba-4dc3-9f1c-c45332e91545.html
html/b3a51d93-8faf-400b-bfb1-b6c7bc38d169.html
html/ba075aa8-c77a-485a-a4c6-b917e47505b0.html
html/c5aa1f14-ec89-4e44-a400-cc2acc15aa0b.html
html/c67a4d4d-21d9-406c-a577-869b9f6b5bda.html
html/d11f0413-114d-48db-9d75-87ed4620fc16.html
html/ea400c3c-cdf4-408a-a33c-d31d14e04639.html
html/ee8c00fd-c3b2-41ba-aade-b7d732ee872e.html
html/f7913271-ce3f-4f4d-baf4-0c75a8790351.html

3.4.3 SE and TE Changes - Many of them.

3.4.3 SE and TE Changes - Many of them.
